### PR TITLE
solve 'norminette' fail and fails on folders names including spaces ( except for moulitest & libft-unit-test )

### PR DESCRIPTION
**Pull request by lpoujade**

### CODE REVIEW

**Comment by jgigault** [comment]
Nice job thanks!
Thanks to you I saw a few new things to fix that I will later...

But again one last more thing before I merge....

**That would be great if you rebase your Pull Request** :-)
I wrote a new wiki tip to [rebase a Pull Request](https://github.com/jgigault/42FileChecker/wiki/Contributing-to-42FileChecker#tip1).

It's about making your commit messages less dirty! Could you?

**Comment by lpoujade** [comment]
yes sorry i'm a bit loosed with github i will do that :)

**Comment by lpoujade** [comment]
ok, it's good
I think I don't need re-pul request ?

**Comment by jgigault** [comment]
All right!

**Pull request merged**
