### PR TITLE
norminette

### PR DESCRIPTION
**Pull request by lpoujade**
seems like norminette doesn't accept files names with `norminette "$RET0"`

### CODE REVIEW

**Comment by jgigault** [comment]
Good point! Thanks!

As I don't have access right on your branch patch-1, may be you could add for me an additional error message before I merge :-)

Here is what I mean:
```bash 
if [ "${RET0}" != "" ]
then
    # do things
else
    printf ${C_RED}"  No source file (.c) or header (.h) to be checked"${C_CLEAR}
fi
```

And the complete context:
```bash
		RET0=$(find . -type f | sed '/^\.\/\./d' | grep -E \\.\[hc\]$ | tr '\n' ' ')
		if [ "${RET0}" != "" ]
		then
			RET2=`norminette $RET0 2>&1`
			cd "$RETURNPATH"
			echo "$RET2" > "$RETURNPATH"/.mynorminette
			RET2=`cat .mynorminette | grep Error`
			RET3=`cat .mynorminette | grep Warning`
			RET4=`cat .mynorminette | grep "command not found"`
			if [ "$RET2" == "" -a "$RET3" == "" -a "$RET4" == "" ]
			then
				printf $C_GREEN"  All files passed the tests"$C_CLEAR
			else
				if [ "$RET4" != "" ]
				then
					printf $C_RED"  Command not found"$C_CLEAR
				else
					if [ "$RET2" == "" ]
					then
						TOTAL=0
					else
						TOTAL=`echo "$RET2" | wc -l | sed 's/ //g'`
					fi
					if [ "$RET3" == "" ]
					then
						TOTA2=0
					else
						TOTA2=`echo "$RET3" | wc -l | sed 's/ //g'`
					fi
					(( TOTAL = $TOTAL + $TOTA2 ))
					printf $C_RED"  $TOTAL error(s) or warning(s)"$C_CLEAR
				fi
			fi
		else
			printf ${C_RED}"  No source file (.c) or header (.h) to be checked"${C_CLEAR}
		fi
```

**Comment by jgigault** [comment]
Good point! Thanks!

As I don't have access right on your branch patch-1, may be you could do some changes before I merge :-)

Here is what I mean:
- finding in "$MYPATH"
- add a new error message when no file to be checked
- move the command "cd" juste before the "norminette"

```bash 
RET0=$(find "$MYPATH" -type f | sed '/^\.\/\./d' | grep -E \\.\[hc\]$ | tr '\n' ' ')
if [ "${RET0}" != "" ]
then
    cd "$MYPATH"
    RET2=`norminette $RET0 2>&1`
    cd "$RETURNPATH"

    # do other things

else
    printf ${C_RED}"  No source file (.c) or header (.h) to be checked"${C_CLEAR}
fi
```

And the complete context:
```bash
		RET0=$(find "$MYPATH" -type f | sed '/^\.\/\./d' | grep -E \\.\[hc\]$ | tr '\n' ' ')
		if [ "${RET0}" != "" ]
		then
			cd "$MYPATH"
			RET2=`norminette $RET0 2>&1`
			cd "$RETURNPATH"
			echo "$RET2" > "$RETURNPATH"/.mynorminette
			RET2=`cat .mynorminette | grep Error`
			RET3=`cat .mynorminette | grep Warning`
			RET4=`cat .mynorminette | grep "command not found"`
			if [ "$RET2" == "" -a "$RET3" == "" -a "$RET4" == "" ]
			then
				printf $C_GREEN"  All files passed the tests"$C_CLEAR
			else
				if [ "$RET4" != "" ]
				then
					printf $C_RED"  Command not found"$C_CLEAR
				else
					if [ "$RET2" == "" ]
					then
						TOTAL=0
					else
						TOTAL=`echo "$RET2" | wc -l | sed 's/ //g'`
					fi
					if [ "$RET3" == "" ]
					then
						TOTA2=0
					else
						TOTA2=`echo "$RET3" | wc -l | sed 's/ //g'`
					fi
					(( TOTAL = $TOTAL + $TOTA2 ))
					printf $C_RED"  $TOTAL error(s) or warning(s)"$C_CLEAR
				fi
			fi
		else
			printf ${C_RED}"  No source file (.c) or header (.h) to be checked"${C_CLEAR}
		fi
```

**Comment by jgigault** [comment]
Or may be we can remove the "cd" command as we find files with absolute path.

There is may be another issue:
With paths containing spaces (that's why I used ´"$RET0"´). We should add a backslash before spaces..

**Comment by lpoujade** [comment]
yep I write find $MYPATH instead

**Comment by jgigault** [comment]
Ok cool
I re-wrote the find line to escape spaces with a backslash `\`.

With this new way to list the files...
```bash
RET0=$(find "${MYPATH}" -type f | sed '/^\.\/\./d' | grep -E \\.\[hc\]$ | awk 'BEGIN {ORS=" "} {gsub(/\ /, "\\ "); print}')
```
...we get the absolute path of the files, listed as bellow:
```
/Users/admin/Documents/libft/test1.c /Users/admin/Documents/libft/test2.c /Users/admin/Documents/libft/test3.h
```

So that we can call the norminette from everywhere:
```bash
norminette /Users/admin/Documents/libft/test1.c /Users/admin/Documents/libft/test2.c /Users/admin/Documents/libft/test3.h
```

Tell me if you want me to write the new code, but I would like you to commit this fix.

Thanks

**Comment by jgigault** [comment]
Ok cool.
I re-wrote the way to get the file list to check:
```bash
RET0=$(find "${MYPATH}" -type f | grep -E \\.\[hc\]$ | awk 'BEGIN {ORS=" "} {gsub(/\ /, "\\ "); print}')
```

We now get the absolute path to the files like:
```
/Users/admin/Documents/ma\ libft/test1.c /Users/admin/Documents/ma\ libft/test2.c /Users/admin/Documents/ma\ libft/test3.h
```

So that we do not need to "cd" anymore because the following command will work from every directories:
```bash
norminette /Users/admin/Documents/ma\ libft/test1.c /Users/admin/Documents/ma\ libft/test2.c /Users/admin/Documents/ma\ libft/test3.h
```

We can remove "cd", but we have another issue: Add "eval" before "norminette" to make it work:
```bash
RET2=`eval norminette $RET0 2>&1`
```

Tell me if you want me to change the code, but I would like you to commit this fix

**Comment by lpoujade** [comment]
yep i'm on, it fail here i'm searching why

**Comment by lpoujade** [comment]
I close here, I done one other pull request ( sorry, I have emmêlés mes pinceaux with git )

**Pull request closed without merging**
